/*
Lucca Oliveira Schroder - 201765205AC
Ronan Dos Santos Rosa - 201765026AB
Jaqueline da Silva Amaral Lopes - 201976007
Wendell Guimarães Júnior - 201635032
 */
package br.ufjf.ice.dcc.locadoraveiculos.telas;

import br.ufjf.ice.dcc.locadoraveiculos.Endereco;
import br.ufjf.ice.dcc.locadoraveiculos.Cliente;
import br.ufjf.ice.dcc.locadoraveiculos.Locadora;
import br.ufjf.ice.dcc.locadoraveiculos.PessoaFisica;
import br.ufjf.ice.dcc.locadoraveiculos.PessoaJuridica;
import br.ufjf.ice.dcc.locadoraveiculos.ValidaCpfCnpj;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronan
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();

        //but_cadastroSalvar.setEnabled(false);
        ctext_cadastroID.setEnabled(false);
    }

    public Date converteStringData() throws ParseException {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = formato.parse(ctext_cadastroNascimento.getText());
        return dataFormatada;
    }

    public void limpaCamposCC() {
        ctext_cadastroNome.setText("");
        ctext_cadastroEmail.setText("");
        ctext_cadastroID.setText("");
        ctext_cadastroNascimento.setText("");
        ctext_cadastroTelefone.setText("");
        ctext_endBairro.setText("");
        ctext_endCep.setText("");
        ctext_endCidade.setText("");
        ctext_endComplemento.setText("");
        ctext_endLogra.setText("");
        ctext_endNumero.setText("");
        ctext_endUf.setText("");
    }

    //TRATAMENTO DE EXCEÇÃO
    //VERIFICA SE TODOS CAMPOS DE PESSOA FÍSICA FORAM PREENCHIDOS.
    private boolean verificaCampos(Cliente cliente) {
        cliente.setNome(ctext_cadastroNome.getText());
        cliente.setID(ctext_cadastroID.getText());
        cliente.setEmail(ctext_cadastroEmail.getText());
        cliente.setTelefone(ctext_cadastroTelefone.getText());

        if(rbut_cnpj.isSelected()){
            cliente.setDataNascimento(null);
        }else{
            try {
                cliente.setDataNascimento(converteStringData());
            } catch (NullPointerException | NumberFormatException | ParseException ex) {
                JOptionPane.showMessageDialog(null, "Campos incompletos ou preenchidos incorretamente.");
                return false;
            }
        }    

        if (cliente.getNome().isEmpty() || cliente.getEmail().isEmpty() || cliente.getTelefone().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos.");
            return false;
        }else if(!ValidaCpfCnpj.isValid(cliente.getID())) {
            JOptionPane.showMessageDialog(null, "CPF inválido!");
            return false;
        }else {
            return true;
        }
    }

    

    //VERIFICA SE TODOS CAMPOS DE ENDERECO FORAM PREENCHIDOS.
    private boolean verificaCamposEnd(Endereco endereco) {
        endereco.setLogradouro(ctext_endLogra.getText());
        endereco.setComplemento(ctext_endComplemento.getText());
        endereco.setCep(ctext_endCep.getText());
        endereco.setBairro(ctext_endBairro.getText());
        endereco.setCidade(ctext_endCidade.getText());
        endereco.setEstado(ctext_endUf.getText());

        try {
            endereco.setNumero(Integer.parseInt(ctext_endNumero.getText()));
        } catch (NullPointerException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Campos incompletos ou preenchidos incorretamente.");
            return false;
        }

        if (endereco.getLogradouro().isEmpty()
                || endereco.getBairro().isEmpty() || endereco.getCidade().isEmpty()
                || endereco.getEstado().isEmpty() || endereco.getCep().trim().equals("-")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos.");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_indentificador = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        but_cadastroCancelar = new javax.swing.JButton();
        but_cadastroSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ctext_cadastroNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ctext_cadastroEmail = new javax.swing.JTextField();
        ctext_cadastroID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ctext_cadastroTelefone = new javax.swing.JTextField();
        rbut_cpf = new javax.swing.JRadioButton();
        rbut_cnpj = new javax.swing.JRadioButton();
        ctext_cadastroNascimento = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ctext_endLogra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ctext_endNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ctext_endComplemento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ctext_endBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ctext_endCidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ctext_endUf = new javax.swing.JTextField();
        ctext_endCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastre um novo Cliente");

        but_cadastroCancelar.setText("Cancelar");
        but_cadastroCancelar.setToolTipText("Cancelar");
        but_cadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cadastroCancelarActionPerformed(evt);
            }
        });

        but_cadastroSalvar.setText("Salvar");
        but_cadastroSalvar.setToolTipText("Salvar");
        but_cadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cadastroSalvarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pessoal"));

        jLabel2.setText("Nome");

        ctext_cadastroNome.setToolTipText("Nome completo");
        ctext_cadastroNome.setName("Nome completo"); // NOI18N

        jLabel4.setText("E-mail");

        ctext_cadastroEmail.setToolTipText("Email");
        ctext_cadastroEmail.setName("Nome completo"); // NOI18N

        ctext_cadastroID.setToolTipText("Identificador");
        ctext_cadastroID.setName("Nome completo"); // NOI18N

        jLabel7.setText("Data de Nascimento");

        jLabel5.setText("Telefone");

        ctext_cadastroTelefone.setToolTipText("Telefone");
        ctext_cadastroTelefone.setName("Nome completo"); // NOI18N

        bg_indentificador.add(rbut_cpf);
        rbut_cpf.setText("CPF");
        rbut_cpf.setToolTipText("CPF");
        rbut_cpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbut_cpfMouseClicked(evt);
            }
        });

        bg_indentificador.add(rbut_cnpj);
        rbut_cnpj.setText("CNPJ");
        rbut_cnpj.setToolTipText("CNPJ");
        rbut_cnpj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbut_cnpjMouseClicked(evt);
            }
        });

        try {
            ctext_cadastroNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ctext_cadastroNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctext_cadastroNascimento.setToolTipText("Data de Nascimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbut_cpf)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctext_cadastroNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ctext_cadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(rbut_cnpj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ctext_cadastroID)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctext_cadastroTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(ctext_cadastroNascimento))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ctext_cadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctext_cadastroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rbut_cpf)
                    .addComponent(rbut_cnpj)
                    .addComponent(ctext_cadastroNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctext_cadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ctext_cadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço"));

        jLabel8.setText("Logradouro");

        ctext_endLogra.setToolTipText("Logradouro");
        ctext_endLogra.setName("Nome completo"); // NOI18N

        jLabel9.setText("CEP");

        jLabel6.setText("Número");

        ctext_endNumero.setToolTipText("Número");

        jLabel10.setText("Complemento");

        ctext_endComplemento.setToolTipText("Complemento");

        jLabel11.setText("Bairro");

        ctext_endBairro.setToolTipText("Bairro");

        jLabel12.setText("Cidade");

        ctext_endCidade.setToolTipText("Cidade");

        jLabel13.setText("UF");

        ctext_endUf.setToolTipText("UF");

        try {
            ctext_endCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ctext_endCep.setToolTipText("CEP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ctext_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctext_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctext_endUf, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ctext_endCep, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctext_endComplemento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ctext_endLogra)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctext_endNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ctext_endLogra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ctext_endNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(ctext_endComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctext_endCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ctext_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ctext_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ctext_endUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ctext_endLogra.getAccessibleContext().setAccessibleName("Nome completo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(but_cadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(but_cadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_cadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_cadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void but_cadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cadastroCancelarActionPerformed
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_cadastroCancelarActionPerformed

    private void but_cadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cadastroSalvarActionPerformed
        Endereco endereco = new Endereco();
        Cliente cliente = null;

        if (verificaCamposEnd(endereco)) {
            //VERIFICA SE ALGUM JBOTTOM FOI SELECIONADO
            if (rbut_cpf.isSelected()){ 
                cliente = new PessoaFisica();
                if (verificaCampos(cliente) ) {
                    if (!Locadora.verificaCliente((PessoaFisica) cliente)) {
                        cliente.setEndereco(endereco);
                        Locadora.adicionaCliente((PessoaFisica) cliente);
                        limpaCamposCC();
                        JOptionPane.showMessageDialog(null, "Cliente Cadastrado.");
                    }else
                    JOptionPane.showMessageDialog(null, "Cliente já está Cadastrado!");
                }
            }else if( rbut_cnpj.isSelected()){
                cliente = new PessoaJuridica();
                if (verificaCampos(cliente) ) {
                    if (!Locadora.verificaCliente((PessoaJuridica) cliente)) {
                        cliente.setEndereco(endereco);
                        Locadora.adicionaCliente((PessoaJuridica) cliente);
                        limpaCamposCC();
                        JOptionPane.showMessageDialog(null, "Cliente Cadastrado.");
                    }else
                    JOptionPane.showMessageDialog(null, "Cliente já está Cadastrado!");
                }
                
            }else {
                JOptionPane.showMessageDialog(null, "Selecione um Indentificador.");
            }
        }

        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_cadastroSalvarActionPerformed

    private void rbut_cnpjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbut_cnpjMouseClicked
        ctext_cadastroNascimento.setText("");
        ctext_cadastroNascimento.setEnabled(false);
        ctext_cadastroID.setEnabled(true);
    }//GEN-LAST:event_rbut_cnpjMouseClicked

    private void rbut_cpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbut_cpfMouseClicked
        ctext_cadastroNascimento.setEnabled(true);
        ctext_cadastroID.setEnabled(true);
    }//GEN-LAST:event_rbut_cpfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_indentificador;
    private javax.swing.JButton but_cadastroCancelar;
    private javax.swing.JButton but_cadastroSalvar;
    private javax.swing.JTextField ctext_cadastroEmail;
    private javax.swing.JTextField ctext_cadastroID;
    private javax.swing.JFormattedTextField ctext_cadastroNascimento;
    private javax.swing.JTextField ctext_cadastroNome;
    private javax.swing.JTextField ctext_cadastroTelefone;
    private javax.swing.JTextField ctext_endBairro;
    private javax.swing.JFormattedTextField ctext_endCep;
    private javax.swing.JTextField ctext_endCidade;
    private javax.swing.JTextField ctext_endComplemento;
    private javax.swing.JTextField ctext_endLogra;
    private javax.swing.JTextField ctext_endNumero;
    private javax.swing.JTextField ctext_endUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbut_cnpj;
    private javax.swing.JRadioButton rbut_cpf;
    // End of variables declaration//GEN-END:variables
}
